# Ablation: Only C2f_AK (No CoordAtt)
nc: 10
scales:
  n: [0.33, 0.25, 1024]

backbone:
  - [-1, 1, Conv, [64, 3, 2]]
  - [-1, 1, Conv, [128, 3, 2]]
  - [-1, 3, C2f_AK, [128, True]]
  - [-1, 1, Conv, [256, 3, 2]]
  - [-1, 6, C2f_AK, [256, True]]
  - [-1, 1, Conv, [512, 3, 2]]
  - [-1, 6, C2f_AK, [512, True]]
  - [-1, 1, Conv, [1024, 3, 2]]
  - [-1, 3, C2f_AK, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]] # 9层之后没有CA了

head:
  - [-1, 1, nn.Upsample, [None, 2, 'nearest']] # 10 (原11)
  - [[-1, 6], 1, Concat, [1]] # 11
  - [-1, 3, C2f_AK, [512]] # 12

  - [-1, 1, nn.Upsample, [None, 2, 'nearest']] # 13
  - [[-1, 4], 1, Concat, [1]] # 14
  - [-1, 3, C2f_AK, [256]] # 15

  - [-1, 1, Conv, [256, 3, 2]] # 16
  - [[-1, 12], 1, Concat, [1]] # 17 (原18, 指向现在的12)
  - [-1, 3, C2f_AK, [512]] # 18

  - [-1, 1, Conv, [512, 3, 2]] # 19
  - [[-1, 9], 1, Concat, [1]] # 20 (关键：原21连的是10CA，现在连9层SPPF)
  - [-1, 3, C2f_AK, [1024]] # 21

  - [[15, 18, 21], 1, Detect, [nc]] # 22 (索引全部对应改变)
